version: '2'
services:
  bussappweb-app:
    image: bussappweb
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bussappweb-postgresql:5432/bussAppWeb
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://bussappweb-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bussappweb-elasticsearch:9200
    ports:
      - 8080:8080
  bussappweb-postgresql:
    extends:
      file: postgresql.yml
      service: bussappweb-postgresql
  bussappweb-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: bussappweb-elasticsearch
